name: Clang-Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install clang-format
      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get update
          apt-cache policy llvm-18-dev

      # Run clang-format check
      - name: Run clang-format
        run: |
          FILES=$(git ls-files "*.cpp" "*.hpp")
          echo "$FILES" | xargs clang-format-18 --dry-run --Werror
