name: Clang Format Checker

on:
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clang Format Github Action
        uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: "src/**/*.c,include/**/*.h"
          style: ".clang-format"
