name: Clang-Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install clang-format (choose version you want, e.g., clang-format-14)
      - name: Install clang-format
        run: |
          wget -O clang-format-18.deb https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-18/clang-format-18_18.1.8~%2B%2B20240731024944%2B3b5b5c1ec4a3-1~exp1~20240731145000.144_amd64.deb
          sudo apt-get -f install
#          sudo dpkg -i clang-format-18.deb
#          sudo apt-get update && sudo apt-get install -y clang-format-18

      # Run clang-format check
      - name: Run clang-format
        run: |
          FILES=$(git ls-files "*.cpp" "*.hpp")
          echo "$FILES" | xargs clang-format-18 --dry-run --Werror
